[project]
name = "general-local-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.6.0",
    "langchain>=1.0.2",
    "langchain-core>=1.0.0",
    "langgraph>=1.0.1",
]
